name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: shubham11196
        password: Missudadi@@1

    - name: Build Docker Image
      run: docker build -t cicd-pipeline .

    - name: Push to Docker Hub
      run: docker push shubham11196/cicd-pipeline:latest
